from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_DIR = PROJECT_ROOT / "dataset"
DEFAULT_SEQUENCE_LENGTH = 30
DEFAULT_MODEL_PATH = PROJECT_ROOT / "models" / "exercise_bilstm.keras"
DEFAULT_PROCESSED_DATASET = DATASET_DIR / "processed" / "exercise_sequences.npz"


@dataclass(frozen=True)
class ExerciseConfig:
    name: str
    display_name: str
    rep_metric: str
    tracked_angle_label: str
    up_threshold: float
    down_threshold: float
    muscle_groups: str
    coaching_focus: str
    tips: str
    realtime_ready: bool = True
    dataset_group: str = ""
    benchmark_hint: str = ""


EXERCISE_CONFIGS = {
    "barbell_bench_press": ExerciseConfig(
        name="barbell_bench_press",
        display_name="Barbell Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=162.0,
        down_threshold=82.0,
        muscle_groups="Chest, front delts, triceps",
        coaching_focus="Bar path control, elbow depth, and lockout",
        tips="Keep feet planted, lower under control, and press evenly.",
        realtime_ready=False,
        dataset_group="horizontal_press",
        benchmark_hint="Use custom videos plus Kinetics/UCF push-up-like pressing motions only for pretraining.",
    ),
    "flat_bench_press": ExerciseConfig(
        name="flat_bench_press",
        display_name="Flat Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=162.0,
        down_threshold=82.0,
        muscle_groups="Chest, front delts, triceps",
        coaching_focus="Bar depth and stable press path",
        tips="Keep wrists stacked and drive the bar evenly upward.",
        realtime_ready=False,
        dataset_group="horizontal_press",
        benchmark_hint="Best trained from your own side-view benchmark set.",
    ),
    "incline_bench_press": ExerciseConfig(
        name="incline_bench_press",
        display_name="Incline Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Upper chest, shoulders, triceps",
        coaching_focus="Upper-chest press path and elbow control",
        tips="Keep the shoulder blades set and avoid flaring too early.",
        realtime_ready=False,
        dataset_group="incline_press",
        benchmark_hint="Mostly requires custom data; public datasets are weak here.",
    ),
    "overhead_press": ExerciseConfig(
        name="overhead_press",
        display_name="Overhead Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=92.0,
        muscle_groups="Shoulders, triceps",
        coaching_focus="Vertical press lockout and symmetry",
        tips="Brace the core and press in a vertical path close to the face.",
        dataset_group="vertical_press",
        benchmark_hint="Combine custom standing press videos with NTU-style skeleton sequences.",
    ),
    "push_up": ExerciseConfig(
        name="push_up",
        display_name="Push-Up",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=90.0,
        muscle_groups="Chest, shoulders, triceps",
        coaching_focus="Controlled depth, symmetry, and full lockout",
        tips="Keep the body straight, lower the chest with control, and press evenly.",
        dataset_group="push",
        benchmark_hint="A strong class for both public datasets and real-time webcam coaching.",
    ),
    "military_press": ExerciseConfig(
        name="military_press",
        display_name="Military Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=92.0,
        muscle_groups="Front delts, triceps",
        coaching_focus="Vertical press lockout and controlled descent",
        tips="Keep the rib cage down and avoid leaning back.",
        dataset_group="vertical_press",
        benchmark_hint="Treat as the same class family as overhead press.",
    ),
    "incline_dumbbell_fly": ExerciseConfig(
        name="incline_dumbbell_fly",
        display_name="Incline Dumbbell Fly",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=120.0,
        muscle_groups="Upper chest, shoulders",
        coaching_focus="Controlled arc and equal arm path",
        tips="Maintain a soft elbow bend and avoid dropping too deep.",
        realtime_ready=False,
        dataset_group="chest_fly",
        benchmark_hint="Public benchmarks are limited; prioritize your own labeled videos.",
    ),
    "cable_fly": ExerciseConfig(
        name="cable_fly",
        display_name="Cable Fly",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=118.0,
        muscle_groups="Chest",
        coaching_focus="Symmetry and controlled contraction",
        tips="Keep elbows soft and bring hands together without shrugging.",
        realtime_ready=False,
        dataset_group="chest_fly",
        benchmark_hint="Requires custom gym footage because cable stations occlude joints.",
    ),
    "dumbbell_fly": ExerciseConfig(
        name="dumbbell_fly",
        display_name="Dumbbell Fly",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=118.0,
        muscle_groups="Chest",
        coaching_focus="Arm path symmetry and chest squeeze",
        tips="Move in a wide arc and keep the shoulder joint controlled.",
        realtime_ready=False,
        dataset_group="chest_fly",
        benchmark_hint="Best supported by your own side-angle videos.",
    ),
    "lateral_raise": ExerciseConfig(
        name="lateral_raise",
        display_name="Lateral Raise",
        rep_metric="avg_shoulder",
        tracked_angle_label="Shoulder angle",
        up_threshold=82.0,
        down_threshold=22.0,
        muscle_groups="Side delts",
        coaching_focus="Raise height and arm symmetry",
        tips="Lift to shoulder height and avoid swinging from the torso.",
        dataset_group="lateral_raise",
        benchmark_hint="Custom data plus shoulder-abduction actions from broad datasets.",
    ),
    "tricep_pushdown": ExerciseConfig(
        name="tricep_pushdown",
        display_name="Tricep Pushdown",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=152.0,
        down_threshold=70.0,
        muscle_groups="Triceps",
        coaching_focus="Full elbow extension without shoulder sway",
        tips="Keep elbows pinned and press down without rocking backward.",
        realtime_ready=False,
        dataset_group="tricep_extension",
        benchmark_hint="Custom cable-machine data is needed for strong accuracy.",
    ),
    "skull_crusher": ExerciseConfig(
        name="skull_crusher",
        display_name="Skull Crusher",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=68.0,
        muscle_groups="Triceps",
        coaching_focus="Elbow flexion and extension control",
        tips="Keep the upper arm steady and extend without flaring.",
        realtime_ready=False,
        dataset_group="tricep_extension",
        benchmark_hint="Use custom bench-based videos; public benchmarks are weak here.",
    ),
    "overhead_tricep_extension": ExerciseConfig(
        name="overhead_tricep_extension",
        display_name="Overhead Tricep Extension",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=165.0,
        down_threshold=72.0,
        muscle_groups="Triceps",
        coaching_focus="Controlled overhead elbow extension",
        tips="Keep elbows close to the head and avoid arching the back.",
        dataset_group="tricep_extension",
        benchmark_hint="Treat as an overhead triceps family; rely on custom data.",
    ),
    "dips": ExerciseConfig(
        name="dips",
        display_name="Dips",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Chest, triceps",
        coaching_focus="Depth and shoulder safety",
        tips="Lower with control and avoid dumping the shoulders forward.",
        dataset_group="dip",
        benchmark_hint="Good candidate for custom side-view videos only.",
    ),
    "barbell_row": ExerciseConfig(
        name="barbell_row",
        display_name="Barbell Row",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=85.0,
        muscle_groups="Back, lats, rear delts",
        coaching_focus="Torso hinge stability and row height",
        tips="Hold the hip hinge and pull elbows back evenly.",
        dataset_group="row",
        benchmark_hint="Map rows and rowing-like actions from custom data plus limited public clips.",
    ),
    "seated_cable_row": ExerciseConfig(
        name="seated_cable_row",
        display_name="Seated Cable Row",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=150.0,
        down_threshold=82.0,
        muscle_groups="Mid back, lats",
        coaching_focus="Scapular retraction and even pull",
        tips="Stay upright and finish with elbows driving behind the torso.",
        realtime_ready=False,
        dataset_group="row",
        benchmark_hint="Machine occlusion means custom videos are required.",
    ),
    "lat_pulldown": ExerciseConfig(
        name="lat_pulldown",
        display_name="Lat Pulldown",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=72.0,
        muscle_groups="Lats, upper back",
        coaching_focus="Bar path and elbow pull-down symmetry",
        tips="Pull toward the upper chest and avoid leaning too far back.",
        realtime_ready=False,
        dataset_group="vertical_pull",
        benchmark_hint="Treat together with pull-ups at the class-family level.",
    ),
    "pull_up": ExerciseConfig(
        name="pull_up",
        display_name="Pull-Up",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Lats, upper back, biceps",
        coaching_focus="Full hang to chin-up motion with symmetry",
        tips="Start from a controlled hang and pull without kicking.",
        dataset_group="vertical_pull",
        benchmark_hint="Public data exists, especially in broad action datasets.",
    ),
    "face_pull": ExerciseConfig(
        name="face_pull",
        display_name="Face Pull",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=150.0,
        down_threshold=88.0,
        muscle_groups="Rear delts, upper back",
        coaching_focus="Elbow flare path and upper-back squeeze",
        tips="Pull toward eye level and rotate outward smoothly.",
        realtime_ready=False,
        dataset_group="rear_delt_pull",
        benchmark_hint="Mostly custom cable footage.",
    ),
    "barbell_curl": ExerciseConfig(
        name="barbell_curl",
        display_name="Barbell Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=150.0,
        down_threshold=52.0,
        muscle_groups="Biceps",
        coaching_focus="Strict elbow flexion without torso swing",
        tips="Keep elbows by your sides and do not use momentum.",
        dataset_group="curl",
        benchmark_hint="Good real-time candidate with custom front-view videos.",
    ),
    "bicep_curl": ExerciseConfig(
        name="bicep_curl",
        display_name="Bicep Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=65.0,
        muscle_groups="Biceps",
        coaching_focus="Strict elbow flexion without torso swing",
        tips="Keep elbows by your sides and curl without using momentum.",
        dataset_group="curl",
        benchmark_hint="Public support is weaker than the core 6 classes, so treat as an extra class if clean clips are available.",
    ),
    "hammer_curl": ExerciseConfig(
        name="hammer_curl",
        display_name="Hammer Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=148.0,
        down_threshold=52.0,
        muscle_groups="Brachialis, biceps",
        coaching_focus="Neutral-grip elbow flexion without sway",
        tips="Keep the thumbs up and lift under control.",
        dataset_group="curl",
        benchmark_hint="Treat as a curl family subclass in training.",
    ),
    "preacher_curl": ExerciseConfig(
        name="preacher_curl",
        display_name="Preacher Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=145.0,
        down_threshold=48.0,
        muscle_groups="Biceps",
        coaching_focus="Strict supported curl path",
        tips="Lower fully with control and avoid bouncing off the pad.",
        realtime_ready=False,
        dataset_group="curl",
        benchmark_hint="Bench support changes the pose; gather custom labeled data.",
    ),
    "squat": ExerciseConfig(
        name="squat",
        display_name="Bodyweight Squat",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=165.0,
        down_threshold=95.0,
        muscle_groups="Quads, glutes, hamstrings",
        coaching_focus="Depth, knee balance, and controlled ascent",
        tips="Keep chest proud, knees stable, and drive upward through the heels.",
        dataset_group="squat",
        benchmark_hint="Strong public support from action-recognition datasets and your own videos.",
    ),
    "barbell_squat": ExerciseConfig(
        name="barbell_squat",
        display_name="Barbell Squat",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=165.0,
        down_threshold=95.0,
        muscle_groups="Quads, glutes, hamstrings",
        coaching_focus="Depth, knee tracking, and torso control",
        tips="Keep the chest up, sit between the hips, and drive evenly upward.",
        dataset_group="squat",
        benchmark_hint="Can share the same skeleton class family as squat, then fine-tune on custom barbell videos.",
    ),
    "lunges": ExerciseConfig(
        name="lunges",
        display_name="Lunges",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=165.0,
        down_threshold=88.0,
        muscle_groups="Quads, glutes, hamstrings",
        coaching_focus="Front knee control and balanced depth",
        tips="Step into the lunge with control and push back up evenly.",
        dataset_group="lunge",
        benchmark_hint="Public support is available in UCF101; use it as a phase-1 class.",
    ),
    "bulgarian_split_squat": ExerciseConfig(
        name="bulgarian_split_squat",
        display_name="Bulgarian Split Squat",
        rep_metric="avg_knee",
        tracked_angle_label="Front knee angle",
        up_threshold=165.0,
        down_threshold=85.0,
        muscle_groups="Quads, glutes",
        coaching_focus="Front-leg depth and balance",
        tips="Lower straight down and keep the front knee tracking over the foot.",
        dataset_group="single_leg_squat",
        benchmark_hint="Mostly custom data; single-leg stance is distinct from standard squats.",
    ),
    "deadlift": ExerciseConfig(
        name="deadlift",
        display_name="Deadlift",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=170.0,
        down_threshold=92.0,
        muscle_groups="Back, glutes, hamstrings",
        coaching_focus="Hip hinge and spinal position",
        tips="Hinge from the hips, keep the bar close, and stand tall at lockout.",
        dataset_group="hip_hinge",
        benchmark_hint="Custom side-view data is essential for good form scoring.",
    ),
    "romanian_deadlift": ExerciseConfig(
        name="romanian_deadlift",
        display_name="Romanian Deadlift",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=170.0,
        down_threshold=100.0,
        muscle_groups="Hamstrings, glutes",
        coaching_focus="Controlled hinge depth and bar path",
        tips="Keep a soft knee bend and push the hips back during descent.",
        dataset_group="hip_hinge",
        benchmark_hint="Train together with deadlift family, then fine-tune.",
    ),
    "calf_raise": ExerciseConfig(
        name="calf_raise",
        display_name="Calf Raise",
        rep_metric="avg_knee",
        tracked_angle_label="Lower-body extension",
        up_threshold=178.0,
        down_threshold=160.0,
        muscle_groups="Calves",
        coaching_focus="Full plantar-flexion and pause at the top",
        tips="Rise through the toes and pause briefly before lowering.",
        realtime_ready=False,
        dataset_group="calf_raise",
        benchmark_hint="Landmarks from a full-body webcam are often too weak for fine accuracy here.",
    ),
}
