from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_DIR = PROJECT_ROOT / "dataset"
DEFAULT_SEQUENCE_LENGTH = 30
DEFAULT_MODEL_PATH = PROJECT_ROOT / "models" / "exercise_bilstm.keras"
DEFAULT_PROCESSED_DATASET = DATASET_DIR / "processed" / "exercise_sequences.npz"


@dataclass(frozen=True)
class ExerciseConfig:
    name: str
    display_name: str
    rep_metric: str
    tracked_angle_label: str
    up_threshold: float
    down_threshold: float
    muscle_groups: str
    coaching_focus: str
    tips: str
    realtime_ready: bool = True
    dataset_group: str = ""
    benchmark_hint: str = ""


# Only includes the 26 exercises the model was trained on (see models/label_names.json)
EXERCISE_CONFIGS = {
    "barbell_bench_press": ExerciseConfig(
        name="barbell_bench_press",
        display_name="Barbell Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=162.0,
        down_threshold=82.0,
        muscle_groups="Chest, front delts, triceps",
        coaching_focus="Bar path control, elbow depth, and lockout",
        tips="Keep feet planted, lower under control, and press evenly.",
        realtime_ready=False,
        dataset_group="horizontal_press",
        benchmark_hint="Use custom videos plus Kinetics/UCF push-up-like pressing motions only for pretraining.",
    ),
    "barbell_curl": ExerciseConfig(
        name="barbell_curl",
        display_name="Barbell Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=150.0,
        down_threshold=52.0,
        muscle_groups="Biceps",
        coaching_focus="Strict elbow flexion without torso swing",
        tips="Keep elbows by your sides and do not use momentum.",
        dataset_group="curl",
        benchmark_hint="Good real-time candidate with custom front-view videos.",
    ),
    "barbell_row": ExerciseConfig(
        name="barbell_row",
        display_name="Barbell Row",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=85.0,
        muscle_groups="Back, lats, rear delts",
        coaching_focus="Torso hinge stability and row height",
        tips="Hold the hip hinge and pull elbows back evenly.",
        dataset_group="row",
        benchmark_hint="Map rows and rowing-like actions from custom data plus limited public clips.",
    ),
    "barbell_squat": ExerciseConfig(
        name="barbell_squat",
        display_name="Barbell Squat",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=165.0,
        down_threshold=95.0,
        muscle_groups="Quads, glutes, hamstrings",
        coaching_focus="Depth, knee tracking, and torso control",
        tips="Keep the chest up, sit between the hips, and drive evenly upward.",
        dataset_group="squat",
        benchmark_hint="Can share the same skeleton class family as squat, then fine-tune on custom barbell videos.",
    ),
    "bicep_curl": ExerciseConfig(
        name="bicep_curl",
        display_name="Bicep Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=65.0,
        muscle_groups="Biceps",
        coaching_focus="Strict elbow flexion without torso swing",
        tips="Keep elbows by your sides and curl without using momentum.",
        dataset_group="curl",
        benchmark_hint="Public support is weaker than the core 6 classes, so treat as an extra class if clean clips are available.",
    ),
    "cable_fly": ExerciseConfig(
        name="cable_fly",
        display_name="Cable Fly",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=155.0,
        down_threshold=118.0,
        muscle_groups="Chest",
        coaching_focus="Symmetry and controlled contraction",
        tips="Keep elbows soft and bring hands together without shrugging.",
        realtime_ready=False,
        dataset_group="chest_fly",
        benchmark_hint="Requires custom gym footage because cable stations occlude joints.",
    ),
    "deadlift": ExerciseConfig(
        name="deadlift",
        display_name="Deadlift",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=170.0,
        down_threshold=92.0,
        muscle_groups="Back, glutes, hamstrings",
        coaching_focus="Hip hinge and spinal position",
        tips="Hinge from the hips, keep the bar close, and stand tall at lockout.",
        dataset_group="hip_hinge",
        benchmark_hint="Custom side-view data is essential for good form scoring.",
    ),
    "decline_bench_press": ExerciseConfig(
        name="decline_bench_press",
        display_name="Decline Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Lower chest, triceps",
        coaching_focus="Controlled descent and even press path",
        tips="Keep elbows at 45 degrees and press through the lower chest.",
        realtime_ready=False,
        dataset_group="horizontal_press",
        benchmark_hint="Custom decline-bench footage required for good accuracy.",
    ),
    "dips": ExerciseConfig(
        name="dips",
        display_name="Dips",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Chest, triceps",
        coaching_focus="Depth and shoulder safety",
        tips="Lower with control and avoid dumping the shoulders forward.",
        dataset_group="dip",
        benchmark_hint="Good candidate for custom side-view videos only.",
    ),
    "flat_bench_press": ExerciseConfig(
        name="flat_bench_press",
        display_name="Flat Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=162.0,
        down_threshold=82.0,
        muscle_groups="Chest, front delts, triceps",
        coaching_focus="Bar depth and stable press path",
        tips="Keep wrists stacked and drive the bar evenly upward.",
        realtime_ready=False,
        dataset_group="horizontal_press",
        benchmark_hint="Best trained from your own side-view benchmark set.",
    ),
    "hammer_curl": ExerciseConfig(
        name="hammer_curl",
        display_name="Hammer Curl",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=148.0,
        down_threshold=52.0,
        muscle_groups="Brachialis, biceps",
        coaching_focus="Neutral-grip elbow flexion without sway",
        tips="Keep the thumbs up and lift under control.",
        dataset_group="curl",
        benchmark_hint="Treat as a curl family subclass in training.",
    ),
    "hip_thrust": ExerciseConfig(
        name="hip_thrust",
        display_name="Hip Thrust",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=165.0,
        down_threshold=90.0,
        muscle_groups="Glutes, hamstrings",
        coaching_focus="Full hip extension at the top and controlled descent",
        tips="Drive through the heels and squeeze the glutes at the top.",
        dataset_group="hip_hinge",
        benchmark_hint="Custom side-view videos are required for accurate landmark tracking.",
    ),
    "incline_bench_press": ExerciseConfig(
        name="incline_bench_press",
        display_name="Incline Bench Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Upper chest, shoulders, triceps",
        coaching_focus="Upper-chest press path and elbow control",
        tips="Keep the shoulder blades set and avoid flaring too early.",
        realtime_ready=False,
        dataset_group="incline_press",
        benchmark_hint="Mostly requires custom data; public datasets are weak here.",
    ),
    "lat_pulldown": ExerciseConfig(
        name="lat_pulldown",
        display_name="Lat Pulldown",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=72.0,
        muscle_groups="Lats, upper back",
        coaching_focus="Bar path and elbow pull-down symmetry",
        tips="Pull toward the upper chest and avoid leaning too far back.",
        realtime_ready=False,
        dataset_group="vertical_pull",
        benchmark_hint="Treat together with pull-ups at the class-family level.",
    ),
    "lateral_raise": ExerciseConfig(
        name="lateral_raise",
        display_name="Lateral Raise",
        rep_metric="avg_shoulder",
        tracked_angle_label="Shoulder angle",
        up_threshold=82.0,
        down_threshold=22.0,
        muscle_groups="Side delts",
        coaching_focus="Raise height and arm symmetry",
        tips="Lift to shoulder height and avoid swinging from the torso.",
        dataset_group="lateral_raise",
        benchmark_hint="Custom data plus shoulder-abduction actions from broad datasets.",
    ),
    "leg_extension": ExerciseConfig(
        name="leg_extension",
        display_name="Leg Extension",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=170.0,
        down_threshold=80.0,
        muscle_groups="Quads",
        coaching_focus="Full knee extension and controlled lowering",
        tips="Extend fully and lower with control without using momentum.",
        realtime_ready=False,
        dataset_group="knee_extension",
        benchmark_hint="Machine-based exercise; custom seated footage is required.",
    ),
    "leg_raises": ExerciseConfig(
        name="leg_raises",
        display_name="Leg Raises",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=80.0,
        down_threshold=15.0,
        muscle_groups="Lower abs, hip flexors",
        coaching_focus="Controlled leg raise and slow lowering",
        tips="Keep the lower back pressed into the floor and raise with control.",
        dataset_group="core",
        benchmark_hint="Public core exercise datasets help; supplement with your own clips.",
    ),
    "military_press": ExerciseConfig(
        name="military_press",
        display_name="Military Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=92.0,
        muscle_groups="Front delts, triceps",
        coaching_focus="Vertical press lockout and controlled descent",
        tips="Keep the rib cage down and avoid leaning back.",
        dataset_group="vertical_press",
        benchmark_hint="Treat as the same class family as overhead press.",
    ),
    "overhead_press": ExerciseConfig(
        name="overhead_press",
        display_name="Overhead Press",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=168.0,
        down_threshold=92.0,
        muscle_groups="Shoulders, triceps",
        coaching_focus="Vertical press lockout and symmetry",
        tips="Brace the core and press in a vertical path close to the face.",
        dataset_group="vertical_press",
        benchmark_hint="Combine custom standing press videos with NTU-style skeleton sequences.",
    ),
    "plank": ExerciseConfig(
        name="plank",
        display_name="Plank",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=180.0,
        down_threshold=160.0,
        muscle_groups="Core, shoulders, glutes",
        coaching_focus="Straight body line and hip alignment",
        tips="Keep the hips level with the body and breathe steadily.",
        dataset_group="core",
        benchmark_hint="Isometric hold; rep counter is time-based rather than angle-based.",
    ),
    "pull_up": ExerciseConfig(
        name="pull_up",
        display_name="Pull-Up",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=78.0,
        muscle_groups="Lats, upper back, biceps",
        coaching_focus="Full hang to chin-up motion with symmetry",
        tips="Start from a controlled hang and pull without kicking.",
        dataset_group="vertical_pull",
        benchmark_hint="Public data exists, especially in broad action datasets.",
    ),
    "push_up": ExerciseConfig(
        name="push_up",
        display_name="Push-Up",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=160.0,
        down_threshold=90.0,
        muscle_groups="Chest, shoulders, triceps",
        coaching_focus="Controlled depth, symmetry, and full lockout",
        tips="Keep the body straight, lower the chest with control, and press evenly.",
        dataset_group="push",
        benchmark_hint="A strong class for both public datasets and real-time webcam coaching.",
    ),
    "romanian_deadlift": ExerciseConfig(
        name="romanian_deadlift",
        display_name="Romanian Deadlift",
        rep_metric="avg_hip",
        tracked_angle_label="Hip angle",
        up_threshold=170.0,
        down_threshold=100.0,
        muscle_groups="Hamstrings, glutes",
        coaching_focus="Controlled hinge depth and bar path",
        tips="Keep a soft knee bend and push the hips back during descent.",
        dataset_group="hip_hinge",
        benchmark_hint="Train together with deadlift family, then fine-tune.",
    ),
    "russian_twist": ExerciseConfig(
        name="russian_twist",
        display_name="Russian Twist",
        rep_metric="avg_shoulder",
        tracked_angle_label="Shoulder angle",
        up_threshold=60.0,
        down_threshold=10.0,
        muscle_groups="Obliques, core",
        coaching_focus="Rotational control and balanced reach each side",
        tips="Rotate through the torso, not just the arms, and keep the feet lifted.",
        dataset_group="core",
        benchmark_hint="Custom front-view footage works best for oblique rotation tracking.",
    ),
    "squat": ExerciseConfig(
        name="squat",
        display_name="Bodyweight Squat",
        rep_metric="avg_knee",
        tracked_angle_label="Knee angle",
        up_threshold=165.0,
        down_threshold=95.0,
        muscle_groups="Quads, glutes, hamstrings",
        coaching_focus="Depth, knee balance, and controlled ascent",
        tips="Keep chest proud, knees stable, and drive upward through the heels.",
        dataset_group="squat",
        benchmark_hint="Strong public support from action-recognition datasets and your own videos.",
    ),
    "tricep_pushdown": ExerciseConfig(
        name="tricep_pushdown",
        display_name="Tricep Pushdown",
        rep_metric="avg_elbow",
        tracked_angle_label="Elbow angle",
        up_threshold=152.0,
        down_threshold=70.0,
        muscle_groups="Triceps",
        coaching_focus="Full elbow extension without shoulder sway",
        tips="Keep elbows pinned and press down without rocking backward.",
        realtime_ready=False,
        dataset_group="tricep_extension",
        benchmark_hint="Custom cable-machine data is needed for strong accuracy.",
    ),
}
